const types = {
    LOG_IN: "LOG_IN",
    LOG_OUT: "LOG_OUT",
    SIGN_UP: "SIGN_UP",
    REFRESH: "REFRESH",
    SET_BOOKS: "SET_BOOKS",
    GET_REVIEWS: "GET_REVIEWS",
    ADD_NEW_REVIEW: "ADD_NEW_REVIEW",
    SET_CURRENT_BOOK: "SET_CURRENT_BOOK",
    UPDATE_CURRENT_BOOK: "UPDATE_CURRENT_BOOK",
    ADD_TO_CART: "ADD_TO_CART"
}
export default types;