const types = {
    LOG_IN: "LOG_IN",
    LOG_OUT: "LOG_OUT",
    SIGN_UP: "SIGN_UP",
    REFRESH: "REFRESH",
    SET_BOOKS: "SET_BOOKS",
    GET_REVIEWS: "GET_REVIEWS",
    ADD_NEW_REVIEW: "ADD_NEW_REVIEW",
    SET_CURRENT_BOOK: "SET_CURRENT_BOOK",
    UPDATE_CURRENT_BOOK: "UPDATE_CURRENT_BOOK",
    CART_ADD_REMOVE: "CART_ADD_REMOVE",
    FAVORIS_ADD_REMOVE: "FAVORIS_ADD_REMOVE",
    QUANTITY_INCREMENT: "QUANTITY_INCREMENT",
    QUANTITY_DECREMENT: "QUANTITY_DECREMENT",
    CHANGE_AVATAR: "CHANGE_AVATAR"
}
export default types;